### ISSUE TITLE
동작하지 않는 가로 스크롤(?)이 보여요

### ISSUE THREAD

**Issue by 2ssue** [connect-foundation/2019-20#72]
### 어떤 버그가 존재하나요?

![image](https://user-images.githubusercontent.com/42017052/70300777-c413f200-183b-11ea-93ac-7f74df609402.png)

가격 아래에 동작하지 않는 가로스크롤이 있습니다!
옆에 제안 받기 글자도 깨지고 있어요

### 기대했던 결과

가로 스크롤이 없거나 가로스크롤이 동작해 제안 받기가 짤리지 않는다.

### 버그 재현 방법

1. 들어갔더니 나왔습니다. 
2. 
3. 

### 체크리스트
- [ ] 해당 이슈와 유사한 선행 이슈가 없는 것을 확인 하였는가
- [ ] 해당 이슈가 프로젝트의 목적과 부합되는가
- [ ] 한 번 더 재현 방법을 실행 해 봤는가
- [ ] 이슈 제목은 직관적인가
- [ ] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [ ] 적절한 라벨을 추가하였는가
- [ ] 모든 필수 항목을 작성하였는가

**Comment by Johnie-Yeo** [comment]
해결되었습니다! 의견 감사합니다.
