### ISSUE TITLE
[Design Issue] 가로화면으로 돌렸을 때 등록 버튼 아래에 TextArea가 깔려있습니다.

### ISSUE THREAD

**Issue by 2ssue** [connect-foundation/2019-20#73]
### 어떤 버그가 존재하나요?

![image](https://user-images.githubusercontent.com/42017052/70301021-88c5f300-183c-11ea-9399-e72acd9ec813.png)

모바일 가로화면일 때 등록버튼 아래에 TextArea가 이미지처럼 깔려있어요.

### 기대했던 결과

등록이 화면에 맞게 맨 아래에 있고, 그 위에 TextArea가 있다.

### 버그 재현 방법

1. 모바일 가로화면으로 해당 페이지에 접근한다. 
2. 
3. 

### 체크리스트
- [ ] 해당 이슈와 유사한 선행 이슈가 없는 것을 확인 하였는가
- [ ] 해당 이슈가 프로젝트의 목적과 부합되는가
- [ ] 한 번 더 재현 방법을 실행 해 봤는가
- [ ] 이슈 제목은 직관적인가
- [ ] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [ ] 적절한 라벨을 추가하였는가
- [ ] 모든 필수 항목을 작성하였는가

**Comment by Johnie-Yeo** [comment]
해결되었습니다 감사합니다!
