### ISSUE TITLE
같은 유저가 접속을했을때 채팅이 여러번 표현됩니다.

### ISSUE THREAD

**Issue by Junow** [connect-foundation/2019-20#76]
### 어떤 버그가 존재하나요?
같은 유저가 접속을했을때 채팅이 여러번 표현됩니다.
물론 테스트용 계정이라 그랬겠지만
아까 확인하신 것처럼 DB, socket 등등의 이슈가 겹쳐 있는 것 같습니다.

추가적으로, 제 컴퓨터에서는 4번씩 나오고 다른 사람 컴퓨터에서는 2번씩 나오는등 랜덤하게 발생하는 이슈도 있는 것 같습니다.

### 기대했던 결과
매끄러운 채팅이 하고 싶었어요 ㅠ

### 버그 재현 방법

1. 채팅방에 접속한다. (아이디 1,2)
2. 채팅을 한다.
3. 

#### Desktop (아래 정보를 기재해 주세요):

 - OS: [Mac]
 - Browser [Chrome]

### 체크리스트
- [ ] 해당 이슈와 유사한 선행 이슈가 없는 것을 확인 하였는가
- [ ] 해당 이슈가 프로젝트의 목적과 부합되는가
- [ ] 한 번 더 재현 방법을 실행 해 봤는가
- [ ] 이슈 제목은 직관적인가
- [ ] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [ ] 적절한 라벨을 추가하였는가
- [ ] 모든 필수 항목을 작성하였는가

**Comment by sukjae** [comment]
의견 감사합니다
이슈 #75 와 중복되어 close 합니다!
